/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bean.DanhMucBean;
import controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        
        setTitle("Quản lý kho hàng");
        ChuyenManHinhController chuyenmanhinh = new ChuyenManHinhController(body);
        chuyenmanhinh.setView(jlbTrangChu); //set default body
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu",jlbTrangChu));
        listItem.add(new DanhMucBean("NhapKho",jlbNhapKho));
        listItem.add(new DanhMucBean("XuatKho",jlbXuatKho));
        listItem.add(new DanhMucBean("HoanTra",jlbHoanTra));
        listItem.add(new DanhMucBean("KhoBai",jlbKhoBai));
        listItem.add(new DanhMucBean("NhaCungCap",jlbNhaCungCap));
        listItem.add(new DanhMucBean("NhanVien",jlbNhanVien));
        listItem.add(new DanhMucBean("KhachHang",jlbKhachHang));
        listItem.add(new DanhMucBean("VatTu",jlbVatTu));
        listItem.add(new DanhMucBean("ThongKe",jlbThongKe));
        
        chuyenmanhinh.setEvent(listItem);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        navigation = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jlbNhapKho = new javax.swing.JLabel();
        jlbXuatKho = new javax.swing.JLabel();
        jlbHoanTra = new javax.swing.JLabel();
        jlbVatTu = new javax.swing.JLabel();
        jlbNhaCungCap = new javax.swing.JLabel();
        jlbKhoBai = new javax.swing.JLabel();
        jlbNhanVien = new javax.swing.JLabel();
        jlbKhachHang = new javax.swing.JLabel();
        jlbThongKe = new javax.swing.JLabel();
        infoUser = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(204, 204, 204));

        header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-warehouse-60.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        navigation.setLayout(new java.awt.GridLayout(1, 0));

        jlbTrangChu.setBackground(new java.awt.Color(0, 0, 0));
        jlbTrangChu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 0, 0));
        jlbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTrangChu.setText("Trang chủ");
        navigation.add(jlbTrangChu);

        jlbNhapKho.setBackground(new java.awt.Color(153, 255, 51));
        jlbNhapKho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbNhapKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNhapKho.setText("Nhập kho");
        navigation.add(jlbNhapKho);

        jlbXuatKho.setBackground(new java.awt.Color(153, 255, 51));
        jlbXuatKho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbXuatKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbXuatKho.setText("Xuất kho");
        navigation.add(jlbXuatKho);

        jlbHoanTra.setBackground(new java.awt.Color(153, 255, 51));
        jlbHoanTra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbHoanTra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHoanTra.setText("Hoàn trả");
        navigation.add(jlbHoanTra);

        jlbVatTu.setBackground(new java.awt.Color(153, 255, 51));
        jlbVatTu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbVatTu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbVatTu.setText("Vật tư");
        navigation.add(jlbVatTu);

        jlbNhaCungCap.setBackground(new java.awt.Color(153, 255, 51));
        jlbNhaCungCap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNhaCungCap.setText("Nhà cung cấp");
        navigation.add(jlbNhaCungCap);

        jlbKhoBai.setBackground(new java.awt.Color(153, 255, 51));
        jlbKhoBai.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbKhoBai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKhoBai.setText("Kho bãi");
        navigation.add(jlbKhoBai);

        jlbNhanVien.setBackground(new java.awt.Color(153, 255, 51));
        jlbNhanVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNhanVien.setText("Nhân viên");
        navigation.add(jlbNhanVien);

        jlbKhachHang.setBackground(new java.awt.Color(153, 255, 51));
        jlbKhachHang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbKhachHang.setText("Khách hàng");
        navigation.add(jlbKhachHang);

        jlbThongKe.setBackground(new java.awt.Color(153, 255, 51));
        jlbThongKe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongKe.setText("Thống kê");
        navigation.add(jlbThongKe);

        jButton1.setText("Đăng xuất");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel10.setText("Trần Trung Hiếu");

        javax.swing.GroupLayout infoUserLayout = new javax.swing.GroupLayout(infoUser);
        infoUser.setLayout(infoUserLayout);
        infoUserLayout.setHorizontalGroup(
            infoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoUserLayout.setVerticalGroup(
            infoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navigation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        body.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JPanel infoUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbHoanTra;
    private javax.swing.JLabel jlbKhachHang;
    private javax.swing.JLabel jlbKhoBai;
    private javax.swing.JLabel jlbNhaCungCap;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbNhapKho;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JLabel jlbVatTu;
    private javax.swing.JLabel jlbXuatKho;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel navigation;
    // End of variables declaration//GEN-END:variables
}
