/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.FindById;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.PhieuNhap;
import model.PhieuNhapChiTiet;
import service.ConnectDB;
import table.TableCustom;

/**
 *
 * @author Admin
 */
public class NhapKho extends javax.swing.JPanel {

    /**
     * Creates new form NhapKho
     */
    public static PhieuNhap phieuNhap;
    public static PhieuNhapChiTiet phieuNhapChiTiet;
    public static int idState;
    public static String code;
    private DefaultTableModel tblPhieuNhapModel;
    private DefaultTableModel tblPhieuNhapChiTietModel;
    private boolean selectTable = false;
    public NhapKho() throws SQLException {
        initComponents();
        initTable("PhieuNhap");
        initTable("PhieuNhapChiTiet");
        loadDataToTable("");
//        loadDataToTableChiTiet("");
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT); //or MULTI_LINE
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        txtphieunhap = new javax.swing.JLabel();
        txtPhieuNhapChiTiet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuNhapChiTiet = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-more-30.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-30.png"))); // NOI18N
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-pencil-30.png"))); // NOI18N
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-available-updates-30.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap())
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsearch)
                    .addGroup(searchLayout.createSequentialGroup()
                        .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRefresh)
                            .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd)
                                .addComponent(btnEdit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Mã phiếu xuất", "Ngày xuất", "Khách hàng", "Nhân viên", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.setAlignmentX(1.0F);
        tblPhieuNhap.setAlignmentY(1.0F);
        tblPhieuNhap.setShowGrid(true);
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuNhap);
        if (tblPhieuNhap.getColumnModel().getColumnCount() > 0) {
            tblPhieuNhap.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblPhieuNhap.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblPhieuNhap.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblPhieuNhap.getColumnModel().getColumn(3).setPreferredWidth(30);
            tblPhieuNhap.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblPhieuNhap.getColumnModel().getColumn(5).setPreferredWidth(30);
            tblPhieuNhap.getColumnModel().getColumn(6).setPreferredWidth(70);
        }

        txtphieunhap.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        txtphieunhap.setForeground(new java.awt.Color(51, 51, 51));
        txtphieunhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtphieunhap.setText("Phiếu nhập : {Id: Loading ; Mã: Loading}");

        txtPhieuNhapChiTiet.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        txtPhieuNhapChiTiet.setForeground(new java.awt.Color(51, 51, 51));
        txtPhieuNhapChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPhieuNhapChiTiet.setText("Phiếu nhập chi tiết");

        tblPhieuNhapChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPhieuNhapChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên vật tư", "Số lượng", "Đơn giá", "Thành tiền", "Vị tri hàng trong kho", "Ghi chú"
            }
        ));
        tblPhieuNhapChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieuNhapChiTiet);

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtphieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhieuNhapChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtphieunhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPhieuNhapChiTiet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        // TODO add your handling code here:
        selectTable = true;
        try {
            int row = tblPhieuNhap.getSelectedRow();
            if (row >= 0) {
                int id = (int) tblPhieuNhap.getValueAt(row, 1);
                phieuNhap = new FindById().phieuNhap(id);
                code = phieuNhap.getCode();
                idState = phieuNhap.getId();
                System.out.println("id phieu nhap: "+idState);
                txtphieunhap.setText("Phiếu nhập: {id:"+idState+"} ; {code:"+code+"}");
                System.out.println(phieuNhap.toString());
                loadDataToTableChiTiet(idState, "");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (selectTable == true) {
            PopupPhieuNhap popupPhieuNhap = null;
            try {
                popupPhieuNhap = new PopupPhieuNhap();
            } catch (Exception ex) {
                Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
            }
            popupPhieuNhap.setVisible(true);
            popupPhieuNhap.setHideAdd();
        } else {
            try {
                PopupPhieuNhapChiTiet popupPhieuNhapChiTiet = new PopupPhieuNhapChiTiet();
                popupPhieuNhapChiTiet.setVisible(true);
                popupPhieuNhapChiTiet.setHideAdd();
            } catch (SQLException ex) {
                Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        PopupPhieuNhap popupPhieuNhap = null;
        try {
            popupPhieuNhap = new PopupPhieuNhap();
        } catch (Exception ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (selectTable == false) {
            popupPhieuNhap.setVisible(true);
            popupPhieuNhap.setHideEditDelete();
        } else{
            try {
                PopupPhieuNhapChiTiet popupPhieuNhapChiTiet = new PopupPhieuNhapChiTiet();
                popupPhieuNhapChiTiet.setVisible(true);
                popupPhieuNhapChiTiet.setHideEditDelete();
            } catch (SQLException ex) {
                Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblPhieuNhapChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapChiTietMouseClicked
        // TODO add your handling code here:
        selectTable = false;
         try {
            int row = tblPhieuNhapChiTiet.getSelectedRow();
            if (row >= 0) {
                int id = (int) tblPhieuNhapChiTiet.getValueAt(row, 1);
                System.out.println("id: "+id);
                phieuNhapChiTiet = new FindById().phieuNhapChiTiet(id);
                txtPhieuNhapChiTiet.setText("Phiếu nhập chi tiết: {Id:"+Integer.toString(id)+"}");
                System.out.println(phieuNhapChiTiet.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblPhieuNhapChiTietMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            loadDataToTable(txtsearch.getText());
        } catch (SQLException ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            loadDataToTable("");
            loadDataToTableChiTiet(idState, "");
        } catch (SQLException ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel search;
    private javax.swing.JPanel table;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTable tblPhieuNhapChiTiet;
    private javax.swing.JLabel txtPhieuNhapChiTiet;
    private javax.swing.JLabel txtphieunhap;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private void initTable(String nameTable) {
        switch (nameTable) {
            case "PhieuNhap":
                tblPhieuNhapModel = new DefaultTableModel();
                tblPhieuNhapModel.setColumnIdentifiers(new String[]{"STT","ID","Mã Code","Ngày Nhập","Nhà Cung Cấp","Nhân Viên","Tổng Tiền","Ghi Chú"});
                tblPhieuNhap.setModel(tblPhieuNhapModel);
                break;
            case "PhieuNhapChiTiet":
                tblPhieuNhapChiTietModel = new DefaultTableModel();
                tblPhieuNhapChiTietModel.setColumnIdentifiers(new String[]{"STT","ID","Vật Tư","Đơn giá","Số Lượng","Thành Tiền","Kho hàng","Vị Trí Vật Tư","Ghi Chú"});
                tblPhieuNhapChiTiet.setModel(tblPhieuNhapChiTietModel);
                break;
            default:
                throw new AssertionError();
        }
    }

    public void loadDataToTable(String key) throws SQLException {
        Connection conn = null;
        try {
            DecimalFormat x = new DecimalFormat("###,###,###");
            String sql = "SELECT PHIEUNHAP.Id, Code, OrderEntryDate, Supplier, CONCAT_WS(' ', EmployeeLastName, EmployeeFirstName) AS hoten, TotalAmount, Description\n" +
                "FROM dbo.PHIEUNHAP LEFT JOIN dbo.NHACUNGCAP\n" +
                "ON NHACUNGCAP.Id = PHIEUNHAP.SupplierId LEFT JOIN dbo.NHANVIEN\n" +
                "ON NHANVIEN.Id = PHIEUNHAP.EmployeeId\n" +
                "WHERE PHIEUNHAP.IsDeleted = 0 AND (Supplier LIKE N'%"+key+"%' OR CONCAT_WS(' ', EmployeeLastName, EmployeeFirstName) LIKE N'%"+key+"%')";
            conn = ConnectDB.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            int i = 1;
            tblPhieuNhapModel.setRowCount(0);
            while (rs.next()) {                
                tblPhieuNhapModel.addRow(new Object[]{
                    i++,
                    rs.getInt("Id"),
                    rs.getString("Code"),
                    rs.getDate("OrderEntryDate"),
                    rs.getString("Supplier"),
                    rs.getString("hoten"),
                    x.format(rs.getInt("TotalAmount")),
                    rs.getString("Description")
                });
            }
            tblPhieuNhapModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        } finally{
            conn.close();
        }
    }

    private void loadDataToTableChiTiet(int idPhieuNhap, String key) throws SQLException {
        Connection conn = null;
        try {
            DecimalFormat x = new DecimalFormat("###,###,###");
            String sql = "SELECT PHIEUNHAPCHITIET.Id, SuppliesName, Quantity, SupplyAmount, TotalAmount, \n" +
                    "KHOHANG.Name, VITRIKHOHANG.Name as namevtkho,PHIEUNHAPCHITIET.Description\n" +
                    "FROM dbo.PHIEUNHAPCHITIET LEFT JOIN dbo.VATTU\n" +
                    "ON VATTU.Id = PHIEUNHAPCHITIET.SupplyId\n" +
                    "LEFT JOIN dbo.VITRIKHOHANG\n" +
                    "ON VITRIKHOHANG.Id = PHIEUNHAPCHITIET.LocationId\n" +
                    "LEFT JOIN dbo.KHOHANG ON KHOHANG.Id = VITRIKHOHANG.WarehouseId\n" +
                    "WHERE PHIEUNHAPCHITIET.IsDeleted = 0 AND Quantity !=0 AND SuppliesName LIKE N'%"+key+"%' AND StockReceivedDocketId = "+idPhieuNhap;
            conn = ConnectDB.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            int i = 1;
            tblPhieuNhapChiTietModel.setRowCount(0);
            while (rs.next()) {                
                tblPhieuNhapChiTietModel.addRow(new Object[]{
                    i++,
                    rs.getInt("Id"),
                    rs.getString("SuppliesName"),
                    x.format(rs.getInt("SupplyAmount")),
                    x.format(rs.getInt("Quantity")),
                    x.format(rs.getInt("TotalAmount")),
                    rs.getString("Name"),
                    rs.getString("namevtkho"),
                    rs.getString("Description")
                });
            }
            tblPhieuNhapChiTietModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        } finally{
            conn.close();
        }
    }
}
