/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import Dao.VatTuDao;
//import Model.VATTU;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
//import Dao.ConnectDB;
//import Dao.KhoDao;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class VatTu extends javax.swing.JPanel {

    /**
     * Creates new form VatTu
     */
    private DefaultTableModel tblModel;
    private DefaultComboBoxModel cbxModel;
    public VatTu() {
        initComponents();
        initTable();
//        loadDataToTable();
        initComboBox();
    }

//    private String CreateID() throws Exception{
//        List<VATTU> list = new VatTuDao().findAll("");  
//        if (true) {
//            int index = list.size()-1;
//            VATTU vt = list.get(index);
//            int idNumber = Integer.parseInt(vt.getId_vt().substring(2)) + 1; //id next        
//            if (idNumber < 10) {
//                return "vt00"+String.valueOf(idNumber);
//            }
//            else if (idNumber >= 10 && idNumber <100) {
//                return "vt0"+String.valueOf(idNumber);
//            }
//            return "vt"+String.valueOf(idNumber);
//        }
//        return "vt001";
//    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID vat tu","Ten vat tu","Loai vat tu","Don vi tinh","ID kho"});
        tblVatTu.setModel(tblModel);
    }
    
//    private void loadDataToTable(){
//        try {
//            String key = txttimkiem.getText();
//            VatTuDao dao = new VatTuDao();
//            List<VATTU> list = dao.findAll(key);
//            tblModel.setRowCount(0);
//            for(VATTU vt : list){
//                tblModel.addRow(new Object[]{
//                    vt.getId_vt(),
//                    vt.getTen_vt(),
//                    vt.getLoai_vt(),
//                    vt.getDon_vi_tinh(),
//                    vt.getId_kho()
//                });
//            }
//            System.out.println("id vat tu: "+key);
//            tblModel.fireTableDataChanged();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    
    private void initComboBox(){
//        try {
//            String sql = "SELECT id_kho FROM KHO";
//            Connection conn = ConnectDB.getConnection();
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            ResultSet rs = pstmt.executeQuery();
//            cbxidkho.removeAllItems();
//            while(rs.next()){
//                cbxidkho.addItem(rs.getString("id_kho"));
//            }
//            rs.close();
//            pstmt.close();
//            conn.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//            e.printStackTrace();
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidvattu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttenvattu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtloaivt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdvt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxidkho = new javax.swing.JComboBox<>();
        jlbkho = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVatTu = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(112, 159, 157));

        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        nav.setBackground(new java.awt.Color(86, 125, 137));
        nav.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nav.setLayout(new java.awt.GridBagLayout());

        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoi.setText("Moi");
        btnMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        nav.add(btnMoi, new java.awt.GridBagConstraints());

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setText("Them");
        btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        nav.add(btnLuu, new java.awt.GridBagConstraints());

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setText("Sua");
        btnCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        nav.add(btnCapNhat, new java.awt.GridBagConstraints());

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        nav.add(btnXoa, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thong tin vat tu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel1.setText("ID vat tu (*)");

        txtidvattu.setEditable(false);
        txtidvattu.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Ten vat tu (*)");

        jLabel3.setText("Loai vat tu (*)");

        txtloaivt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloaivtActionPerformed(evt);
            }
        });

        jLabel4.setText("Don vi tinh (*)");

        jLabel5.setText("ID kho (*)");

        cbxidkho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxidkhoItemStateChanged(evt);
            }
        });

        jlbkho.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlbkho.setForeground(new java.awt.Color(255, 0, 0));
        jlbkho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbkho.setText("jlbkho");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txttenvattu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtloaivt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdvt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxidkho, javax.swing.GroupLayout.Alignment.LEADING, 0, 139, Short.MAX_VALUE)
                    .addComponent(txtidvattu, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbkho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidvattu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenvattu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtloaivt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxidkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbkho)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblVatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVatTuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVatTu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtloaivtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloaivtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloaivtActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
//        try {
//            // TODO add your handling code here:
//            txtidvattu.setText(CreateID());
//        } catch (Exception ex) {
//            Logger.getLogger(VatTu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        txttenvattu.setText("");
//        txtloaivt.setText("");
//        txtdvt.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
//        // TODO add your handling code here:
//        StringBuilder sb = new StringBuilder();
//        if(txtidvattu.getText().equals("")) sb.append("Ban chua nhap ID vat tu");
//        else if(txttenvattu.getText().equals("")) sb.append("Ban chua nhap ten vat tu");
//        else if(txtloaivt.getText().equals("")) sb.append("Ban chua nhap loai vat tu");
//        else if(txtdvt.getText().equals("")) sb.append("Ban chua nhap dia don vi tinh");
//        if(sb.length()>0){
//           JOptionPane.showMessageDialog(this, sb);
//           return;
//        }
//        try {
//            VATTU vt = new VATTU();
//            String id_kho = (String) cbxidkho.getItemAt(cbxidkho.getSelectedIndex());
//            vt.setId_vt(txtidvattu.getText());
//            vt.setTen_vt(txttenvattu.getText());
//            vt.setLoai_vt(txtloaivt.getText());
//            vt.setDon_vi_tinh(txtdvt.getText());
//            vt.setId_kho(id_kho);
//            if(new VatTuDao().insert(vt)){
//                JOptionPane.showMessageDialog(this,"Vat tu da duoc them vao CSDL");
//                loadDataToTable();
//            }
//            else{
//                JOptionPane.showMessageDialog(this,"Them khong thanh cong");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
//        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat vat tu khong?") == JOptionPane.NO_OPTION){
//            return;
//        }
//        
//        try {
//            VATTU vt = new VATTU();
//            String id_kho = (String) cbxidkho.getItemAt(cbxidkho.getSelectedIndex());
//            vt.setId_vt(txtidvattu.getText());
//            vt.setTen_vt(txttenvattu.getText());
//            vt.setLoai_vt(txtloaivt.getText());
//            vt.setDon_vi_tinh(txtdvt.getText());
//            vt.setId_kho(id_kho);
//            if(new VatTuDao().update(vt)){
//                JOptionPane.showMessageDialog(this,"Vat tu da duoc cap nhat vao CSDL");
//                loadDataToTable();
//            }
//            else{
//                JOptionPane.showMessageDialog(this,"Cap nhat khong thanh cong");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
//        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa vat tu khong?") == JOptionPane.NO_OPTION){
//            return;
//        }
//        try {
//            if (new VatTuDao().delete(txtidvattu.getText())) {
//                JOptionPane.showMessageDialog(this,"Vat tu da duoc xoa khoi CSDL");
//                btnMoiActionPerformed(evt);
//                loadDataToTable();
//            }
//            else{
//                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblVatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVatTuMouseClicked
        // TODO add your handling code here:
//        try {
//            int row = tblVatTu.getSelectedRow();
//            if (row >= 0) {
//                String id = (String) tblVatTu.getValueAt(row, 0);
//                int c = cbxidkho.getItemCount();
//                VATTU vt = new VatTuDao().findByID(id);
//                System.out.println("id vat:" + id);
//                if (vt != null) {
//                    txtidvattu.setText(vt.getId_vt());
//                    txttenvattu.setText(vt.getTen_vt());
//                    txtloaivt.setText(vt.getLoai_vt());
//                    txtdvt.setText(vt.getDon_vi_tinh());
//                    System.out.println("id kho : "+vt.getId_kho());
//                    for(int i =0  ; i < c; i++){
//                        if(vt.getId_kho() == null ? (String) cbxidkho.getItemAt(i) == null : vt.getId_kho().equals((String) cbxidkho.getItemAt(i))){
//                            cbxidkho.setSelectedIndex(i); 
//                            break;
//                        }
//                    }
//                }
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_tblVatTuMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
//        loadDataToTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cbxidkhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxidkhoItemStateChanged
        // TODO add your handling code here:
//        String text = (String) cbxidkho.getSelectedItem();
//        if (text != null) {
//            String namekho = (String) new KhoDao().findByID(text).getTen_kho();
//            jlbkho.setText(namekho);
//        }
    }//GEN-LAST:event_cbxidkhoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxidkho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbkho;
    private javax.swing.JPanel nav;
    private javax.swing.JTable tblVatTu;
    private javax.swing.JTextField txtdvt;
    private javax.swing.JTextField txtidvattu;
    private javax.swing.JTextField txtloaivt;
    private javax.swing.JTextField txttenvattu;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
